name: Deploy to 3.2

on:
  push:
    branches:
      - 3.2
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      # - name: Github Action for wget
      #   uses: wei/wget@v1.1.1
      #   with:
      #     args: -O ~/Downloads/Source_Sans_Pro.zip https://fonts.google.com/download?family=Source%20Sans%20Pro
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      - run: npm run fonts
      - run: npm i
      # N.B. we run build twice for now, as we need to build post-PDF creation to include them in the upload, but if we only build after PDF creation we don't know if there's a build error until PDF's are done (~60 mins currently). This could be addressed with better CI.
      # TODO: we actually really only want to go through the pdf generation process if necessary... maybe we need a flag to start PDF's generating (on commit message?), or some automated way?
      - run: npm run build
      # - run: npm run pdf
      # - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: v3.2
          channelId: live